scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'otel-collector:8888' ]
#      - targets: [ 'otel-collector:8889' ]
  - job_name: 'application1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
  - job_name: 'application2'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace